name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install SSH agent and add private key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Add known hosts
      run: |
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts


    - name: Deploy application
      run: |
        ssh ubuntu@${{ secrets.VM_IP }} << EOF
          cd /home/ubuntu/Machine-Learning-and-Data-Science-Platform
          git pull origin main
          source /home/ubuntu/miniforge3/bin/activate test
          pip install -r requirements.txt
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl reload
        EOF